import random
from pythia.util import MagicString, dice_roll
from typing import Any

preset_surname = [
    "SURNAME-ONESURNAME-TWO"
]

preset_innName = [
    "INN-NAME-ONE INN-NAME-TWO"
]

preset_food = [
    "TRAITS-FOOD FOODS"
]
preset_clothes = [
    "FABRICS CLOTHING",
]

preset_city = [
    "A city of CITY-THEMES. EVENT: CITY-EVENTS.",
]

preset_triplemechanismtrap = [
    "A trap that uses: MECHANISMS, MECHANISMS and MECHANISMS."
]

secret_room = [
    MagicString(lambda:
                "ROOM-THEMES room with ROOM-DETAILS in it."
                + f"{" Delve Shift: DELVE-SHIFTS"
                        if dice_roll(6) == 1 else "" }"
                + "\n"
                ),
]

preset_dungeon = [
    MagicString(lambda: (
                "DUNGEONS dungeon with the following rooms:\n"
                + "".join(f"sROOM"
                            for _ in range(dice_roll(6, 2, True)))
                )),
]

secret_ingredient = [
    str(MagicString(lambda: "".join(
                    f"{dice_roll(4, 2)} INGREDIENTS, "
                    for _ in range(dice_roll(4, 2, True))
                    ))),
]


preset_potion = [
    "\nIngredients: sINGREDIENT"
    + "\n"
    + "Potion of "
    + "POTIONS"
    + "\nColor: COLORS"
    + "\nScent: SCENTS"
    + "\nTaste: TASTES"
    + "\nTexture: TEXTURES",
    "\nIngredients: sINGREDIENT"
    + "\n"
    + "Potion of "
    + "DELUSIONS"
    + "\nColor: COLORS"
    + "\nScent: SCENTS"
    + "\nTaste: TASTES"
    + "\nTexture: TEXTURES",
    "\nIngredients: sINGREDIENT"
    + "\n"
    + "Potion of "
    + "MUTATIONS"
    + "\nColor: COLORS"
    + "\nScent: SCENTS"
    + "\nTaste: TASTES"
    + "\nTexture: TEXTURES",
    "\nIngredients: sINGREDIENT"
    + "\n"
    + "QUALITIES "
    + "potion of "
    + "POTIONS"
    + "\nColor: COLORS"
    + "\nScent: SCENTS"
    + "\nTaste: TASTES"
    + "\nTexture: TEXTURES",
    "\nIngredients: sINGREDIENT"
    + "\n"
    + "QUALITIES "
    + "potion of "
    + "DELUSIONS"
    + "\nColor: COLORS"
    + "\nScent: SCENTS"
    + "\nTaste: TASTES"
    + "\nTexture: TEXTURES",
    "\nIngredients: sINGREDIENT"
    + "\n"
    + "QUALITIES "
    + "potion of "
    + "MUTATIONS"
    + "\nColor: COLORS"
    + "\nScent: SCENTS"
    + "\nTaste: TASTES"
    + "\nTexture: TEXTURES"
]

preset_hexcrawl = [
        "\n" +
        "Location: LOCATIONS.\n" +
        "Traits: PLACE-TRAITS.\n" +
        "Structure: STRUCTURES.\n" +
        "Hazard: TRAVEL-HAZARDS.\n"
]

list_chaosSpells = [
    ""
    + "ELEMENTS "
    + "FORMS",
    ""
    + "EFFECTS "
    + "FORMS",
    ""
    + "EFFECTS "
    + "ELEMENTS",
    ""
    + "QUALITIES "
    + "ELEMENTS "
    + "FORMS",
    ""
    + "QUALITIES "
    + "EFFECTS "
    + "FORMS",
    ""
    + "QUALITIES "
    + "EFFECTS "
    + "ELEMENTS",
    ""
    + "NAMES's "
    + "ELEMENTS "
    + "FORMS",
    ""
    + "NAMES's "
    + "EFFECTS "
    + "FORMS",
    ""
    + "NAMES's "
    + "EFFECTS "
    + "ELEMENTS.",
    ""
    + "NAMES's "
    + "QUALITIES "
    + "ELEMENTS "
    + "FORMS",
    ""
    + "NAMES's "
    + "QUALITIES "
    + "EFFECTS "
    + "FORMS",
    ""
    + "NAMES's "
    + "QUALITIES "
    + "EFFECTS "
    + "ELEMENTS",
]

list_dungeonHazards = [
        "Random Encounter.",
        "Rest or damage.",
        "Torches die.",
        "Dungeon shift: DELVE-SHIFTS.",
        "Sign: SIGNS.",
        "Nothing happens."
]

list_travelHazards = [
        "Random encounter",
        "Damage unless rest",
        "d6 for each perishable and spoiled on 1",
        "TRAVEL-SHIFTS",
        "SIGNS",
        "Nothing happens"
]



list_weather = [
    "Storm.",
    "Heavy rain/snowfall",
    "Cold.",
    "Slight rain/snow fall.",
    "Colder than usual.",
    "Expected/good weather",
    "Warmer than usual.",
    "Wind.",
    "Hot.",
    "Lot's of wind.",
    "Hail/Humidity/Fog/Frost",
]

list_npcReactions = [
    "Abhor.",
    "Hate.",
    "Almost hate.",
    "Really dislike.",
    "Dislike.",
    "Neutral",
    "Like.",
    "Really like.",
    "Almost love.",
    "Love.",
    "Fan."
]

list_carousing = [
    "Accidentally Marries a Stranger" +
    "The character wakes up to find they've entered into a legally binding " +
    "marriage with a total stranger.",
    "In Debt to a Shady Character" +
    "They owe a significant amount of money to a local crime lord after a " +
    "gambling spree.",
    "Got a Mysterious Tattoo" +
    "The character has a strange, possibly magical, tattoo they don’t " +
    "remember getting.",
    "Challenge Gone Wrong" +
    "After bragging about their strength, the character now has to fight a " +
    "local champion or beast.",
    "Lost Their Weapon" +
    "They misplace or pawn their favorite weapon, which is now in someone " +
    "else’s hands.",
    "Sworn Oath of Fealty" +
    "The character drunkenly pledged loyalty to a questionable lord or gang.",
    "Accidentally Sold a Party Member's Gear" +
    "While trying to pawn off some junk, they mistakenly sold an important " +
    "piece of equipment.",
    "Arrested for Disorderly Conduct" +
    "The character spent the night in jail after a wild brawl in a tavern.",
    "Embarrassing Public Performance" +
    "They gave a terrible, cringe-worthy performance at an open mic or "
    "talent show.",
    "Woke up in a Barn" +
    "They wake up the next morning in a barn or some other random location, "
    "miles away from where they started.",
    "Stole Something Important" +
    "The character unknowingly stole a valuable or cursed item from a noble " +
    "or merchant.",
    "Made an Enemy" +
    "They insulted a powerful noble or gang leader, who is now looking for "
    "revenge.",
    "Broke Something Valuable" +
    "During their antics, they smashed a priceless artifact, and the owner " +
    "is furious.",
    "Altered Appearance" +
    "They accidentally ingested a potion that changes their appearance or " +
    "even species temporarily.",
    "Unintended Duel" +
    "The character unknowingly agreed to a duel at dawn with a master " +
    "swordsman.",
    "Accidentally Joined a Cult" +
    "They pledged themselves to a strange cult during a drunken ceremony.",
    "Acquired a Strange Companion" +
    "They now have a new companion — perhaps a strange animal or magical " +
    "creature — that they don’t remember befriending.",
    "Lost All Their Gold" +
    "Their entire purse of gold is missing, likely gambled away or " +
    "pickpocketed.",
    "Owed a Favor to the City Guard" +
    "After causing trouble, they now owe a favor to the local law " +
    "enforcement.",
    "Strange Curse" +
    "After a night of revelry, they’ve been cursed with an odd affliction, " +
    "such as speaking in rhyme or being allergic to magic.",
]

list_careers = [
        "Alchemist",
        "Apothecary",
        "Archer",
        "Armorer",
        "Astrologer",
        "Bard",
        "Blacksmith",
        "Brewer",
        "Cartographer",
        "Chandler (Candle Maker)",
        "Cobbler (Shoemaker)",
        "Cook",
        "Cooper (Barrel Maker)",
        "Courtesan",
        "Diplomat",
        "Druid",
        "Farmer",
        "Fisherman",
        "Fletcher (Arrow Maker)",
        "Fortune Teller",
        "Gladiator",
        "Guard",
        "Healer",
        "Herbalist",
        "Herald",
        "Huntsman",
        "Illuminator (Manuscript Artist)",
        "Innkeeper",
        "Jester",
        "Jeweler",
        "Knight",
        "Leatherworker",
        "Locksmith",
        "Mage",
        "Mason",
        "Merchant",
        "Mercenary",
        "Miner",
        "Monk",
        "Navigator",
        "Noble",
        "Oracle",
        "Painter",
        "Pirate",
        "Plague Doctor",
        "Poet",
        "Priest/Priestess",
        "Ranger",
        "Scribe",
        "Sculptor",
        "Shipwright",
        "Siege Engineer",
        "Silversmith",
        "Smuggler",
        "Soldier",
        "Sorcerer/Sorceress",
        "Spy",
        "Steward",
        "Tailor",
        "Tanner",
        "Tax Collector",
        "Thief",
        "Town Crier",
        "Trader",
        "Trapper",
        "Treasurer",
        "Undertaker",
        "Usurer (Money Lender)",
        "Vintner (Winemaker)",
        "Weaponsmith",
        "Weaver",
        "Woodcutter",
        "Wainwright (Cart Maker)",
        "Witch",
        "Wizard",
        "Warden",
        "Beast Tamer",
        "Sage",
        "Seer",
        "Herbalist",
        "Dragon Slayer",
        "Witch Hunter",
        "Necromancer",
        "Enchanter",
        "Rune Master",
        "Golem Crafter",
        "Elementalist",
        "Warlock",
        "Sellsword",
        "Spy Master",
        "Cleric",
        "Archivist",
        "Courtier",
        "Gambler",
        "Mystic",
        "Inventor",
        "Emissary",
        "Pirate Captain",
        "Rune Scribe",
        "Summoner",
]


list_travelShifts = [
    "CITY-EVENTS",
    "COLORS sky",
    "DELUSIONS",
    "DISASTERS",
    "EFFECTS rain",
    "ELEMENTS rain",
    "FOODS rain",
    "SCENTS",
    "SOUNDS",
    "TASTES rain",
    "TEXTURES rain",
    "WEAPONS rain",
]
list_signs = [
    "HHAZARDS",
    "CLOTHING",
    "ELEMENTS trail",
    "FABRICS scrap",
    "FOODS scraps",
    "MECHANISMS",
    "MISC-ITEMS",
    "ORGANS",
    "SCENTS",
    "SOUNDS",
    "SYMBOLS",
    "TEXTURES trail",
    "TOOLS",
    "WEAPONS",
    "Broken branches",
    "Torn BOOKS",
    "Footprints",
    "Scattered MISC-ITEMS",
    "Empty containers",
    "Displaced soil",
    "Faded writing/graffiti",
    "Disturbed ANIMALS",
    "Burnt matches or ashes",
    "Broken glass",
    "Signs of a campsite",
    "ANIMALS tracks",
    "Unusual vegetation",
]

list_locations = [
    "ELEMENTS field",
    "Tropical Rainforest",
    "Desert",
    "Savanna",
    "Temperate Forest",
    "Taiga (Boreal Forest)",
    "Tundra",
    "Grassland",
    "Wetlands",
    "Coral Reef",
    "Mangrove Forest",
    "Mountain Range",
    "Coastal Cliff",
    "Volcanic Island",
    "Cave System",
    "Arctic Ice Cap",
    "Alpine Meadow",
    "Isolated Island",
    "Floodplain",
    "Urban Environment",
    "Dune System",
    "Bamboo Forest",
    "Salt Flats",
    "Hydrothermal Vent",
    "River Delta",
    "Temperate Rainforest",
    "Chaparral",
    "Steppe",
    "Iceberg Field",
    "Rocky Shoreline",
    "Lowland Tropical Forest",
    "Cypress Swamp",
    "Kelp Forest",
    "Fjords",
    "Oasis",
    "Pine Barrens",
    "Sagebrush Steppe",
    "Flooded Forest",
    "Boreal Peatland",
    "Rugged Highlands",
    "Coastal Marsh",
]

list_structures = [
    "BUILDINGS",
    "Ruined BUILDINGS",
    "DUNGEONS",
    "Inn: INN-NAME-ONE INN-NAME-TWO",
    "ROOMS",
    "Trap: TRAP-EFFECTS, HHAZARDS, "
        + "MECHANISMS",
    "Castle",
    "Keep",
    "Bastion",
    "Drawbridge",
    "Cathedral",
    "Monastery",
    "Abbey",
    "Tavern",
    "Stables",
    "Watchtower",
    "Fortress",
    "Peasant Cottage",
    "Windmill",
    "Bridge",
    "Granary",
    "Siege Engine",
    "Chapel",
]

list_placeTraits = [
    "COLORS",
    "EFFECTS",
    "ELEMENTS",
    "QUALITIES",
    "ROOM-THEMES",
    "SOUNDS",
    "TEXTURES",
    "Arid",
    "Rustic",
    "Majestic",
    "Industrial",
    "Cozy",
    "Chaotic",
    "Tranquil",
    "Foreboding",
    "Fertile",
    "Charming",
    "Squalid",
    "Inviting",
    "Opulent",
    "Sparsely-populated",
    "Cosmopolitan",
    "Secluded",
    "Eclectic",
    "Barren",
    "Melancholic",
    "Gloomy",
    "Radiant",
    "Enchanting",
]


list_delveShifts = [
    "Distant ANIMALS sounds",
    "CITY-EVENTS",
    "DELUSIONS",
    "DISASTERS",
    "ELEMENTS flow",
    "SCENTS",
    "SOUNDS",
    "TRAP-EFFECTS",
    "Light crackling",
    "A tapestry swaying",
    "An empty bed creaking",
    "Parchments rustling",
    "ANIMALS parts on the floor",
    "A lute resting in the corner",
    "TOOLS hanging",
    "An open window rattling",
    "Dust settling on furniture",
    "A flag fluttering",
    "A quill pen rolling",
    "A tapestry depicting a battle scene",
    "A wooden chest slightly ajar",
    "Faded maps on the walls",
    "ANIMALS bones on a shelf",
    "A rusty bellows",
]
list_rooms = [
    "BUILDINGS",
    "DUNGEONS",
    "MECHANISMS",
    "LOCATIONS",
    "STRUCTURES",
    "Great Hall",
    "Bedchamber",
    "Kitchen",
    "Pantry",
    "Dinning Hall",
    "Library",
    "Armory",
    "Sitting Room",
    "Chapel",
    "Court Room",
    "Tower Room",
    "Servants’ Quarters",
    "Study",
    "Larder",
    "Solar",
    "Workshop",
    "Stables",
    "Bathhouse",
    "Herb Garden",
    "Storage Room",
    "Warming Room",
    "Noble’s Quarters",
    "Hallway",
    "Dungeons",
    "Chamber of Secrets",
    "Alchemist’s Lab",
    "Furnace Room",
    "Gardens",
    "Theatre Room",
    "Scribe's Room",
    "Map Room",
    "Treasury",
    "Brewery",
    "Panic Room",
    "Drawing Room",
    "Animal Pen",
    "Cloister",
    "Pigeon Loft",
    "Grooming Room",
    "Chamber of Mirrors",
]
list_roomDetails = [
    "ARCHETYPES",
    "BOOKS",
    "CLOTHING",
    "FABRICS",
    "FOODS",
    "HHAZARDS",
    "INGREDIENTS",
    "MATERIALS",
    "MECHANISMS",
    "MISC-ITEMS",
    "MONSTERS",
    "POTIONS",
    "SCENTS",
    "SIGNS",
    "SOUNDS",
    "STREET-DETAILS",
    "SYMBOLS",
    "TOOLS",
    "TREASURES",
    "WEAPONS",
    "Heavy wooden table",
    "Canopy bed",
    "Tapestries",
    "Chests",
    "Furs and hides",
    "Candlesticks",
    "Herb bundles",
    "A spinning wheel",
    "Iron sconces",
    "A large hearth",
    "Shelves of books",
    "A lute or harp",
    "Ceramic jugs and goblets",
    "A mirror with a wooden frame",
    "A globe or astrolabe",
    "A basin and ewer",
    "Rugs or tapestries on the floor",
    "Painted shutters",
    "ANIMALS parts",
]
list_roomThemes = [
    # Random Activity
    "ACTIVITIES",
    "BOOKS",
    "CITY-THEMES",
    "DOMAINS",
    "EFFECTS",
    "ELEMENTS",
    "ITEM-TRAITS",
    "MAGIC-SCHOOLS",
    "PLACE-TRAITS",
    "Wisdom",
    "Nature",
    "Alchemy",
    "Worship",
    "Battle",
    "Death",
    "Magic",
    "Sacrifice",
    "Fate",
    "Blood",
    "Dreams",
    "Bounty",
    "Chaos",
    "Time",
    "Elemental",
    "Journey",
    "Horror",
    "Wisdom",
    "Mystery",
    "Unity",
]
list_dungeons = [
    "BUILDINGS",
    "ROOMS",
    "STRUCTURES",
    "Prison",
    "Cave",
    "Catacombs",
    "Fortress",
    "Ruined BUILDINGS",
    "ELEMENTS",
    "Temple",
    "Labyrinthine",
    "Necromancer’s",
    "Treasure Vault",
    "Alchemical",
    "Shadow",
    "Arcane",
    "Swamp",
    "Mountain",
    "Basilisk’s Lair",
    "Fungal",
    "Underground City",
    "Pirate’s Hideout",
    "Abandoned Mines",
]
list_trapEffects = [
    "DELVE-SHIFTS",
    "EFFECTS",
    "Binding",
    "Choking",
    "Confounding",
    "Dazing",
    "Disorienting",
    "Electrocuting",
    "Embalming",
    "Engulfing",
    "Ensnaring",
    "Fumbling",
    "Grasping",
    "Hollowing",
    "Illuminating",
    "Inflicting",
    "Knocking",
    "Paralyzing",
    "Petrifying",
    "Radiating",
    "Suffocating",
    "Vaporizing",

]
list_hazards = [
    "ANIMALS",
    "DELUSIONS",
    "DELVE-SHIFTS",
    "DISASTERS",
    "EFFECTS",
    "ELEMENTS",
    "MONSTERS",
    "MUTATIONS",
    "CHAOS-SPELLS",
    "TRAVEL-SHIFTS",
    "WEAPONS",
    "Acidic",
    "Blinding",
    "Burning",
    "Crushing",
    "Cursing",
    "Drowning",
    "Frightening",
    "Freezing",
    "Impalement",
    "Overheating",
    "Poisoning",
    "Radiating",
    "Shocking",
    "Searing",
    "Slicing",
    "Smothering",
    "Spiking",
    "Spreading",
    "Tearing",
    "Wasting",
]
list_mechanisms = [
    "TOOLS",
    "Anchor",
    "Axle",
    "Battering ram",
    "Bellows",
    "Counterweight",
    "Drawbridge",
    "Gearbox",
    "Lever",
    "Magnet",
    "Millstone",
    "Mortar",
    "Nail",
    "Piston",
    "Rope",
    "Seesaw",
    "Sheave",
    "Shutter",
    "Sprocket",
    "Treadmill",
    "Winch",
]
list_activities = [
    "EFFECTS",
    "GOALS",
    "SOUNDS",
    "TACTICS",
    "Adventuring",
    "Apprenticing",
    "Crafting",
    "Digging",
    "Exploring",
    "Farming",
    "Fishing",
    "Gathering",
    "Healing",
    "Hunting",
    "Infiltrating",
    "Meditating",
    "Negotiating",
    "Planning",
    "Researching",
    "Resting",
    "Scouting",
    "Sewing",
    "Tinkering",
    "Wandering",
]


list_qualities = [
    "COLORS",
    "PLACE-TRAITS",
    "SCENTS",
    "SOUNDS",
    "TASTES",
    "TEXTURES",
    "Arcane",
    "Benevolent",
    "Cursed",
    "Deceptive",
    "Divine",
    "Eldritch",
    "Enigmatic",
    "Fateful",
    "Foreboding",
    "Gloomy",
    "Haunting",
    "Mysterious",
    "Ominous",
    "Radiant",
    "Serpentine",
    "Sinister",
    "Surreal",
    "Trepidatious",
    "Transcendent",
    "Twisted",
]
list_effects = [
    "ACTIVITIES",
    "TRAP-EFFECTS",
    "Aging",
    "Amplifying",
    "Annihilating",
    "Blurring",
    "Contorting",
    "Corrupting",
    "Devouring",
    "Disorienting",
    "Dismembering",
    "Emasculating",
    "Ensnaring",
    "Exhausting",
    "Faltering",
    "Frightening",
    "Incapacitating",
    "Manipulating",
    "Obfuscating",
    "Quaking",
    "Severing",
    "Twisting",
]

list_elements = [
    "DOMAINS",
    "FABRICS",
    "FOODS",
    "MATERIALS",
    "Amber",
    "Ash",
    "Crystal",
    "Dew",
    "Ember",
    "Frost",
    "Glass",
    "Gravel",
    "Honey",
    "Ice",
    "Lava",
    "Mist",
    "Mudslide",
    "Petals",
    "Quartz",
    "Rust",
    "Thunder",
    "Twilight",
    "Vapor",
    "Wisp",
]
list_forms = [
    # Random Animal
    "ANIMALS",
    "CLOTHING",
    "MECHANISMS",
    "MISC-ITEMS",
    "MONSTERS",
    "ORGANS",
    "STRUCTURES",
    "SYMBOLS",
    "TOOLS",
    "WEAPONS",
    "Amulet",
    "Anchor",
    "Arc",
    "Bowl",
    "Braid",
    "Cage",
    "Chalice",
    "Emblem",
    "Flame",
    "Hornet",
    "Icon",
    "Orb",
    "Pillar",
    "Quill",
    "Ring",
    "Scepter",
    "Sphere",
    "Staff",
    "Talon",
    "Tower",
]
list_mutations = [
    "Get younger",
    "Get older",
    "ANIMALS body",
    "ANIMALS ears",
    "ANIMALS eyes",
    "ANIMALS form",
    "ANIMALS head",
    "ANIMALS limb",
    "ANIMALS scent",
    "ANIMALS skin",
    "ANIMALS tail",
    "ANIMALS teeth",
    "ANIMALS voice",
    "COLORS skin",
    "ELEMENTS blood",
    "ELEMENTS body",
    "ELEMENTS breath",
    "ELEMENTS sweat",
    # Random Mannerism
    "MANNERISMS",
    # Random MonsterTrait
    "MONSTER-TRAITS",
    # Random NpcDetail
    "NPC-DETAILS",
    # Random Organ
    "ORGANS",
    # Random Personality
    "PERSONALITIES",
    # Random Power
    "POWERS",
    # Random Scent
    "SCENTS",
    # Random Sound
    "SOUNDS",
    # Random Texture
    "TEXTURES body",
    "Animalistic claws",
    "Antennae",
    "Beak replaces mouth",
    "Bioluminescent patches",
    "Branch-like limbs",
    "Chitinous plating",
    "Color-changing skin",
    "Detached shadow",
    "Elongated neck",
    "Exposed bone",
    "Flesh turns to bark",
    "Floating limbs",
    "Glowing eyes",
    "Insect wings",
    "Mouth in palm",
    "Pincer hands",
    "Reptilian eyes",
    "Rotting flesh",
    "Tongue tentacles",
]
list_delusions = [
    # Random Activity
    "ACTIVITIES",
    # Random Animal
    "ANIMALS",
    # Random Asset
    "ASSETS",
    # Random Domain
    "Fears DOMAINS",
    # Random Symbol
    "Fears SYMBOLS",
    # Random Goal
    "GOALS",
    # Random Liability
    "LIABILITIES",
    # Random Mannerism
    "MANNERISMS",
    # Random Mission
    "MISSIONS",
    # Random Monster
    "MONSTERS",
    # Random MonsterTrait
    "MONSTER-TRAITS",
    # Random Name
    "FEMALE-NAMES?, MALE-NAMES?, "
        + "WIZARD-NAMES?",
    # Random NpcDetail
    "NPC-DETAILS",
    # Random Organ
    "ORGANS",
    # Random Personality
    "PERSONALITIES",
    # Random Power
    "POWERS",
    # Random Profession
    "PROFESSIONS",
    # Random Skin
    "SKINS texture",
    # Random Sound
    "SOUNDS",
    # Random Weakness
    "WEAKNESSES",
    # Random WizardName
    "WIZARD-NAMES",
    "Believes they are haunted",
    "Thinks they are a dragon in disguise",
    "Believes they are immune to fire",
    "Convinced they can breathe underwater",
    "Believes they are cursed with bad luck",
    "Thinks they are aging in reverse",
    "Believes they can communicate with stones",
    "Convinced they are constantly watched by gods",
    "Believes they are the only real person",
    "Thinks all doors are portals",
    "Believes their blood is gold",
    "Convinced they are an ancient warrior reborn",
    "Believes they can control time with blinking",
    "Thinks their soul is trapped in an object",
    "Convinced they are already in the afterlife",
    "Believes they are a puppet controlled by someone else",
    "Thinks they can speak to the dead through mirrors",
    "Convinced they are slowly transforming into a tree",
    "Believes the stars control their every action",
    "Thinks they are destined to become a god",
]
list_disasters = [
    # Random Delusion
    "DELUSIONS",
    # Random Effect
    "EFFECTS rain",
    # Random Element
    "ELEMENTS rain",
    # Random Mutation
    "MUTATIONS",
    # Random Texture
    "TEXTURES rain",
    # Random Weapon
    "WEAPONS rain",
    "Air turns toxic",
    "All fire extinguishes",
    "All food spoils",
    "All metal melts",
    "Ashfall from sky",
    "Beasts become giant",
    "Blood rain",
    "Clouds vanish",
    "Cold snap freezes everything",
    "Darkness devours light",
    "Desert expands",
    "Endless eclipse",
    "Forest turns to stone",
    "Insects swarm",
    "Invisible walls form",
    "Land splits apart",
    "Lightning strikes continuously",
    "Mountains crumble",
    "Nightmares become real",
    "Waters recede",
]
list_magicSchools = [
    "Alchemy of Souls",
    "Antipathy",
    "Astral Projection",
    "Blood Magic",
    "Bones",
    "Chaos",
    "Clockwork",
    "Curses",
    "Decay",
    "Elemental Binding",
    "Entropy",
    "Fleshcrafting",
    "Gravitation",
    "Harmonics",
    "Inner Flame",
    "Lunar Magic",
    "Mutation",
    "Reflections",
    "Runecrafting",
    "Void",
]
list_domains = [
    "BOOKS",
    "MAGIC-SCHOOLS",
    "ROOM-THEMES",
    "Air",
    "Animals",
    "Chaos",
    "Death",
    "Earth",
    "Fire",
    "Good",
    "Healing",
    "Knowledge",
    "Law",
    "Life",
    "Luck",
    "Magic",
    "Nature",
    "Protection",
    "Sun",
    "Travel",
    "War",
    "Water",
    "Weather",
]
list_symbols = [
    # Random Animal
    "ANIMALS",
    # Random Clothing
    "CLOTHING",
    # Random Food
    "FOODS",
    # Random Form
    "FORMS",
    # Random MiscItem
    "MISC-ITEMS",
    # Random Organ
    "ORGANS",
    # Random Weapon
    "WEAPONS",
]

list_potions = [
    # Random Animal
    "ANIMALS form",
    # Random Delusion
    "DELUSIONS",
    # Random Effect
    "EFFECTS",
    # Random Element
    "ELEMENTS Form",
    # Random Mannerism
    "MANNERISMS",
    # Random MonsterTrait
    "MONSTER-TRAITS",
    # Random Mutation
    "MUTATIONS",
    # Random NpcDetail
    "NPC-DETAILS",
    # Random Organ
    "ORGANS",
    # Random Personality
    "PERSONALITIES",
    # Random Power
    "POWERS",
    # Random Profession
    "PROFESSIONS",
    "Absorption",
    "Alchemical transformation",
    "Animal form",
    "Aromatherapy",
    "Bubble form",
    "Charm",
    "Chronomancy",
    "Cloaking",
    "Elemental affinity",
    "Emotion-sensing",
    "Empathy",
    "Enhanced agility",
    "Flame-throwing",
    "Giant's strength",
    "Glamour",
    "Illusion",
    "Inspiration",
    "Magnetic pull",
    "Misty step",
    "Night vision",
    "Phoenix rebirth",
    "Potion of clarity",
    "Rejuvenation",
    "Shadow walking",
    "Soul-link",
    "Spiritual guidance",
    "Starlight",
    "Tethering",
    "Weather manipulation",
    "Wind manipulation",

]
list_textures = [
    "Abrasive",
    "Airy",
    "Ambered",
    "Banded",
    "Brittle",
    "Burnished",
    "Craggy",
    "Crinkled",
    "Crusty",
    "Dappled",
    "Decadent",
    "Delicate",
    "Dusty",
    "Eroded",
    "Fibrous",
    "Fleecy",
    "Flimsy",
    "Frosted",
    "Fuzzy",
    "Grainy",
    "Hardened",
    "Hazy",
    "Jagged",
    "Knotty",
    "Matted",
    "Melty",
    "Moist",
    "Mottled",
    "Nubby",
    "Peeled",
    "Pitted",
    "Rustic",
    "Rugged",
    "Saturated",
    "Scaly",
    "Serrated",
    "Silky",
    "Skeletal",
    "Threadbare",
    "Twisted",
]
list_tastes = [
    # Random Animal
    "ANIMALS",
    # Random Food
    "FOODS",
    # Random Scent
    "SCENTS",
    "Acai",
    "Aged cheese",
    "Balsamic vinegar",
    "Bamboo shoots",
    "Bitter melon",
    "Black tea",
    "Buttercup",
    "Chervil",
    "Chili powder",
    "Chocolates",
    "Cilantro",
    "Dandelion",
    "Eucalyptus",
    "Green apple",
    "Honeydew",
    "Lavender",
    "Mulberry",
    "Pomegranate",
    "Szechuan pepper",
    "Tarragon",
]
list_colors = [
    "Black",
    "White",
    "Red",
    "Green",
    "Blue",
    "Yellow",
    "Brown",
    "Gray",
    "Pink",
    "Purple",
    "Orange",
    "Beige",
    "Teal",
    "Turquoise",
    "Navy blue",
    "Lavender",
    "Coral",
    "Indigo",
    "Maroon",
    "Mint green",
    "Cream",
    "Rust",
    "Magenta",
    "Chartreuse",
    "Olive green",
    "Copper",
    "Aqua",
    "Emerald green",
    "Mustard yellow",
    "Peach",
    "Cyan",
    "Fuchsia",
    "Ivory",
    "Sky blue",
    "Plum",
    "Sapphire",
    "Salmon",
    "Amber",
    "Hazel",
    "Cerulean",
    "Chocolate",
    "Sea green",
    "Tan",
    "Pea green",
    "Burnt orange",
    "Periwinkle",
    "Berry",
    "Lilac",
    "Burgundy",
    "Onyx",
]
list_ingredients = [
    # Random Animal
    "ANIMALS",
    # Random Book
    "BOOKS",
    # Random Clothing
    "CLOTHING",
    "ELEMENTS",
    # Random Fabric
    "FABRICS",
    # Random Food
    "FOODS",
    # Random Material
    "MATERIALS",
    # Random MiscItem
    "MISC-ITEMS",
    # Random Monster
    "MONSTERS",
    # Random Organ
    "ORGANS",
    # Random Potion
    "POTIONS",
    "Abalone shell",
    "Aconite",
    "Almond oil",
    "Aloe vera",
    "Ambergris",
    "Amethyst",
    "Angelica",
    "Ash",
    "Astringent bark",
    "Basilisk scale",
    "Bitterroot",
    "Black cohosh",
    "Bloodroot",
    "Blue lotus",
    "Bone dust",
    "Borage",
    "Brass",
    "Cacao",
    "Carob",
    "Cedar wood",
    "Chili powder",
    "Chrysanthemum",
    "Cinnamon bark",
    "Clove oil",
    "Coriander",
    "Crimson thread",
    "Dill",
    "Dragon’s blood resin",
    "Elderflower",
    "Eucalyptus",
    "Fennel",
    "Fire opal",
    "Flaxseed",
    "Garnet",
    "Ginger root",
    "Ginseng",
    "Goosegrass",
    "Grape seed",
    "Green tea",
    "Hemlock extract",
    "Honeycomb",
    "Jade",
    "Juniper berries",
    "Lavender",
    "Lemon balm",
    "Licorice root",
    "Lotus root",
    "Mace",
    "Mallow",
    "Marshmallow root",
    "Milk thistle",
    "Mistletoe",
    "Moringa",
    "Mustard seed",
    "Narcissus",
    "Nettle root",
    "Nutmeg",
    "Oregano",
    "Paprika",
    "Parsley",
    "Peppercorns",
    "Peridot",
    "Pine resin",
    "Pink salt",
    "Poppy seeds",
    "Prickly pear",
    "Quinoa",
]

list_food = [
    # Random Animal
    "ANIMALS",
    # Random Monster
    "MONSTERS",
    # Random Organ
    "ORGANS",
    "Barley",
    "Bread",
    "Cheese",
    "Chickpeas",
    "Coriander",
    "Couscous",
    "Dried fruits",
    "Eggs",
    "Garlic",
    "Honey",
    "Lentils",
    "Mushrooms",
    "Olives",
    "Onions",
    "Peas",
    "Pork",
    "Pigeon",
    "Rice",
    "Rosemary",
    "Salted fish",
    "Spices",
    "Squash",
    "Stews",
    "Turnips",
    "Walnuts",
]

list_clothing = [
    "Apron",
    "Belt",
    "Boots",
    "Breeches",
    "Cape",
    "Cloak",
    "Coat",
    "Doublet",
    "Dress",
    "Frock",
    "Gambeson",
    "Gauntlets",
    "Gloves",
    "Gown",
    "Hat",
    "Hose",
    "Jerkin",
    "Kilt",
    "Kirtle",
    "Mantle",
    "Pants",
    "Petticoat",
    "Robe",
    "Shirt",
    "Shoes",
    "Skirt",
    "Socks",
    "Surcoat",
    "Tunic",
    "Trousers",
    "Vest",
    "Waistcoat",
    "Wimple",
    "Leggings",
    "Duster",
    "Clogs",
    "Cowl",
    "Shawl",
    "Bandana",
    "Scarf",
    "Sleeves",
    "Apron",
    "Bodice",
    "Culottes",
    "Girdle",
    "Bracers",
    "Headband",
    "Tippet",
    "Cap",
    "Wristbands",
]

list_treasures = [
    # Random Book
    "BOOKS",
    # Random Clothing
    "CLOTHING",
    # Random Ingredient
    "INGREDIENTS",
    # Random Material
    "MATERIALS",
    # Random Monster
    "MONSTERS skin",
    # Random Organ
    "ORGANS",
    # Random Potion
    "POTIONS",
    # Random Reward
    "REWARDS",
    # Random Spell
    "CHAOS-SPELLS",
    # Random Weapon
    "WEAPONS"
    "Adventurer's map",
    "Amber necklace",
    "Artisan-crafted dagger",
    "Baking tray",
    "Belt pouch",
    "Bowl of fruit",
    "Brass compass",
    "Ceramic mug",
    "Chest of coins",
    "Cloak pin",
    "Common clothes",
    "Cookbook",
    "Culinary herbs",
    "Cupboard of spices",
    "Dried herbs",
    "Embroidered tapestry",
    "Fishing net",
    "Flint and steel",
    "Folding chair",
    "Gilded frame",
    "Glass vial",
    "Gold ingots",
    "Grooming kit",
    "Leather armor",
    "Leather-bound journal",
    "Mason's tools",
    "Mead barrel",
    "Musical instrument",
    "Noble’s portrait",
    "Oil lamp",
    "Parchment scroll",
    "Pottery jar",
    "Riding saddle",
    "Salt cellar",
    "Scissors",
    "Sewing kit",
    "Sewing needle",
    "Silver goblet",
    "Spoon set",
    "Stoneware jug",
    "Tapestry wall hanging",
    "Thimble",
    "Toolbelt",
    "Traveling trunk",
    "Trowel",
    "Wool blanket",
    "Wrought iron candlestick",
    "Writing quill",
    "Wooden crate",
    "Woven basket",
]
list_tools = [
    "Acid vial",
    "ANIMALS scent",
    "Antitoxin",
    "Astrolabe",
    "Bandoleer",
    "Bear trap",
    "Bedroll",
    "Beeswax",
    "Bell",
    "Bellows",
    "Birdcage",
    "Blank book",
    "Blanket",
    "Block and tackle",
    "Boltcutters",
    "Bottle",
    "Bucket",
    "Bullseye lantern",
    "Caltrops",
    "Candle",
    "Censer",
    "Chain",
    "Chalk",
    "Chisel",
    "Climbing hook",
    "Compass",
    "Copper wire",
    "Crowbar",
    "Dice",
    "Door ram",
    "Ear trumpet",
    "Ether",
    "Fire oil",
    "Fishing hook",
    "Flashbomb",
    "Flashpowder",
    "Garlic",
    "Glue",
    "Grappling hook",
    "Grease",
    "Hacksaw",
    "Hammer",
    "Hand drill",
    "Hemp rope",
    "Hog holder",
    "Hooded lantern",
    "Hourglass",
    "Incense",
    "Iron pot",
    "Lantern",
]
list_miscItems = [
    # Random Book
    "BOOKS",
    # Random Clothing
    "CLOTHING",
    # Random Fabric
    "FABRICS",
    # Random Food
    "FOODS",
    # Random Food
    "FOODS recipe",
    # Random Ingredient
    "INGREDIENTS",
    # Random Material
    "MATERIALS",
    # Random Organ
    "ORGANS",
    # Random Potion
    "POTIONS",
    # Random Potion
    "POTIONS recipe",
    # Random Spell
    "CHAOS-SPELLS scroll",
    # Random Spell
    "CHAOS-SPELLS book",
    # Random Tool
    "TOOLS",
    # Random Treasure
    "TREASURES",
    # Random Weapon
    "WEAPONS",
    "Tooth",
    "Treaty",
    "Tuning fork",
    "Wand",
    "Warrant",
    "Clock",
    "Amulet",
    "Arrowhead",
    "Birdcage",
    "Bowl",
    "Box",
    "Brooch",
    "Button",
    "Card",
    "Cipher",
    "Coin",
    "Comb",
    "Crystal",
    "Cup",
    "Degree",
    "Doll",
    "Drum",
    "Egg",
    "Embroidery",
    "Feather",
    "Figurine",
    "Finger bone",
    "Flag",
    "Flute",
    "Fork",
    "Game piece",
    "Gem",
    "Hair oil",
    "Hairbrush",
    "Handkerchief",
    "Horn",
    "Icon",
    "Jar",
    "Key",
    "Knife",
    "Ladle",
    "Leg bone",
    "Lens",
    "Letter",
    "List of demands",
    "Lock of hair",
    "Locket",
    "Lotion",
    "Lute",
    "Lyre",
]
list_books = [
    # Random CityTheme
    "CITY-THEMES",
    # Random Disaster
    "DISASTERS",
    # Random Domain
    "DOMAINS",
    # Random Dungeon
    "DUNGEONS",
    # Random Faction
    "FACTIONS",
    # Random Magic Schools
    "MAGIC-SCHOOLS",
    # Random Monster
    "MONSTERS",
    # Random Potion
    "POTIONS Recipe",
    # Random Profession
    "PROFESSIONS",
    # Random RoomTheme
    "ROOM-THEMES",
    # Random Spell
    "CHAOS-SPELLS",
    # Random Trap
    "TRAPS",
    "Mathematics",
    "Medicine",
    "Modern history",
    "Adventure novel",
    "Agriculture",
    "Almanac",
    "Anatomy",
    "Ancient history",
    "Archaeology",
    "Architecture",
    "Astrology",
    "Bestiary",
    "Biography",
    "Blackmail",
    "Botany",
    "Calendars",
    "Comedic novel",
    "Commerce",
    "Condemnation",
    "Confession",
    "Conspiracies",
    "Cookbook",
    "Criminal secrets",
    "Cryptography",
    "Culture",
    "Customs",
    "Diplomacy",
    "Divination",
    "Epic poems",
    "Espionage",
    "Ethics",
    "Etiquette",
    "Fashion",
    "Finance",
    "Fishing",
    "Folklore",
    "Genealogy",
    "Geography",
    "Geology",
    "Ghosts",
    "Gods",
    "Hagiography",
    "Heraldry",
    "Horror stories",
    "Hunting",
    "Husbandry",
    "Journal",
    "Language",
    "Laws",
    "Letters",
]
list_weapons = [
    "Arming sword",
    "Backsword",
    "Bardiche",
    "Baton",
    "Battleaxe",
    "Beheading sword",
    "Bill hook",
    "Blowgun",
    "Blowpipe",
    "Boar spear",
    "Bolas",
    "Boomerang",
    "Brass knuckles",
    "Bullet crossbow",
    "Butterfly sword",
    "Censer flail",
    "Cestus",
    "Chain whip",
    "Chakram",
    "Claymore",
    "Club",
    "Crossbow",
    "Cutlass",
    "Dagger",
    "Dao",
    "Deer horn knives",
    "Dirk",
    "Double flail",
    "Emeici",
    "Falchion",
    "Flail",
    "Flambard",
    "Flying claws",
    "Gauntlet sword",
    "Gladius",
    "Glaive",
    "Halberd",
    "Hatchet",
    "Hook sword",
    "Horsebow",
    "Hunting knife",
    "Ice pick",
    "Javelin",
    "Katana",
    "Katar",
    "Khopesh",
    "Kukri",
    "Lance",
    "Longsword",
    "Warhammer",
]
list_foodTraits = [
    # Random Texture
    "TEXTURES",
    "Aged",
    "Bacon-wrapped",
    "Baked",
    "Balls",
    "Barbecued",
    "Basted",
    "Battered",
    "Blackened",
    "Blanched",
    "Boiled",
    "Braised",
    "Breaded",
    "Brined",
    "Broiled",
    "Broth",
    "Browned",
    "Buttered",
    "Cake",
    "Candied",
    "Canned",
    "Caramelized",
    "Casserole",
    "Charred",
    "Chilled",
    "Chowder",
    "Cobbler",
    "Creamed",
    "Crumble",
    "Cubed",
    "Cured",
    "Deep-fried",
    "Diced",
    "Drunk",
    "Emulsified",
    "Fermented",
    "Flambéd",
    "Fondue",
    "Frozen",
    "Glazed",
    "Grilled",
    "Gruel",
    "Hash",
    "Honeyed",
    "Iced",
    "Layered",
    "Marinated",
    "Mashed",
    "Pickled",
    "Poached",
    "Roasted",
]
list_fabrics = [
    # Random Animal
    "ANIMALS skin",
    # Random Monster
    "MONSTERS skin",
    "Alpaca wool",
    "Bamboo weave",
    "Barkcloth",
    "Beaver skin",
    "Blanket wool",
    "Brocade",
    "Calfskin",
    "Camel hair",
    "Camel skin",
    "Canvas",
    "Cashmere wool",
    "Cotton",
    "Cow skin",
    "Damask",
    "Deerskin",
    "Denim (made from cotton)",
    "Felt (made from wool)",
    "Flannel (made from cotton or wool)",
    "Flax (linen)",
    "Fleece (made from wool)",
    "Goatskin",
    "Hemp",
    "Horse hair",
    "Lamb wool",
    "Lambskin",
    "Leather",
    "Linen",
    "Mohair wool",
    "Muslin (made from cotton)",
    "Ostrich skin",
    "Rabbit skin",
    "Reindeer skin",
    "Sheepskin",
    "Sheep wool",
    "Silk",
    "Suede",
    "Taffeta (made from silk)",
    "Tartan (made from wool or cotton)",
    "Tweed (made from wool)",
    "Velvet (made from silk or cotton)",
    "Wool",
    "Yarn (natural fibers)",
    "Jute",
    "Patchwork (made from various natural fabrics)",
    "Coconut fiber (coir)",
    "Raffia",
    "Bamboo fiber",
    "Sisal",
    "Brocade (with natural fibers)",
    "Hemp canvas",
]
list_decorations = [
    # Random Color
    "COLORS",
    # Random ItemTrait
    "ITEM-TRAITS",
    # Random Scent
    "SCENTS",
    # Random Symbol
    "SYMBOLS",
    "Adorned",
    "Aged wood",
    "Animal skins",
    "Antler accents",
    "Armor embellishments",
    "Banners",
    "Beaded fringe",
    "Carved motifs",
    "Celtic knots",
    "Chiseled stone",
    "Colored glass",
    "Decorative shields",
    "Draped fabric",
    "Embroidered patterns",
    "Exotic woods",
    "Feathered accents",
    "Fossils",
    "Framed tapestries",
    "Gilded edges",
    "Glass beads",
    "Grommets",
    "Hanging lanterns",
    "Heraldic banners",
    "Intricate inlays",
    "Ironwork",
    "Jewelry embellishments",
    "Leather lacing",
    "Metal filigree",
    "Mosaic patterns",
    "Natural dyes",
    "Ornate carvings",
    "Painted designs",
    "Patterned fabric",
    "Pewter accents",
    "Plant motifs",
    "Reinforced seams",
    "Rope detailing",
    "Rustic charms",
    "Sculpted figures",
    "Stained glass",
    "Stone carvings",
    "Tassels",
    "Tied knots",
    "Vines and leaves",
    "Woven textures",
    "Wrought iron accents",
    "Zodiac symbols",
    "Woodburned designs",
    "Wreaths",
    "Zodiac motifs",
]
list_materials = [
    "Alabaster",
    "Amber",
    "Bamboo",
    "Bark",
    "Beryl",
    "Bone",
    "Brass",
    "Bronze",
    "Cane",
    "Canvas",
    "Ceramic",
    "Cedar",
    "Clay",
    "Cork",
    "Cotton",
    "Crystal",
    "Ebony",
    "Emerald",
    "Flint",
    "Glass",
    "Gold",
    "Granite",
    "Hemp",
    "Iron",
    "Ivory",
    "Jade",
    "Linen",
    "Mahogany",
    "Marble",
    "Obsidian",
    "Onyx",
    "Paper",
    "Pewter",
    "Platinum",
    "Quartz",
    "Rattan",
    "Redwood",
    "Rope",
    "Sandalwood",
    "Silver",
    "Slate",
    "Soapstone",
    "Steel",
    "Stone",
    "Taffeta",
    "Teak",
    "Thatch",
    "Walnut",
    "Wool",
    "Zinc",
]
list_itemTraits = [
    # Random Color
    "COLORS",
    # Random Effect
    "EFFECTS",
    # Random Element
    "ELEMENTS",
    # Random Personality
    "PERSONALITIES",
    # Random Scent
    "SCENTS",
    # Random Sound
    "SOUNDS",
    # Random Texture
    "TEXTURES",
    "Aged",
    "Ancient",
    "Antique",
    "Barbaric",
    "Battle-worn",
    "Bizarre",
    "Brilliant",
    "Cursed",
    "Dented",
    "Distressed",
    "Durable",
    "Elegant",
    "Enchanted",
    "Exquisite",
    "Feather-light",
    "Flickering",
    "Fragile",
    "Funky",
    "Furry",
    "Gnarled",
    "Handcrafted",
    "Heavy-duty",
    "Illusory",
    "Impervious",
    "Imposing",
    "Inverted",
    "Intricate",
    "Luminous",
    "Mysterious",
    "Obsolete",
    "Ordinary",
    "Perilous",
    "Poisoned",
    "Radiant",
    "Rusty",
    "Sacred",
    "Scorched",
    "Seasoned",
    "Secluded",
    "Shattered",
    "Spiritual",
    "Surreal",
    "Translucent",
    "Unbreakable",
    "Unusual",
    "Victorious",
    "Weathered",
    "Worn",
    "Wretched",
    "Zealous",
]

list_cityThemes = [
    # Random Animal
    "ANIMALS",
    # Random Activity
    "ACTIVITIES",
    # Random Building
    "BUILDINGS",
    # Random CityEvent
    "CITY-EVENTS",
    # Random Delusion
    "DELUSIONS",
    # Random Disaster
    "DISASTERS",
    # Random Domain
    "DOMAINS",
    # Random Dungeon
    "DUNGEONS",
    # Random Element
    "ELEMENTS",
    # Random Faction
    "FACTIONS",
    # Random FactionTrait
    "FACTION-TRAITS",
    # Random Food
    "FOODS",
    # Random Hazard
    "HHAZARDS",
    # Random MagicSchool
    "MAGIC-SCHOOLS",
    # Random Mutation
    "MUTATIONS",
    # Random Profession
    "PROFESSIONS",
    # Random RoomTheme
    "ROOM-THEMES",
    # Random Structure
    "STRUCTURES",
    # Random TravelShift
    "TRAVEL-SHIFTS",
    # Random Treasure
    "TREASURES",
    "Alchemy",
    "FACTIONS Guilds",
    "Animal Husbandry",
    "Artisan Workshops",
    "Astronomy",
    "Bartering",
    "Bazaars",
    "Black Markets",
    "Brassieres",
    "Breweries",
    "Caravans",
    "Chariots",
    "Circuses",
    "Craftsmanship",
    "Crematoriums",
    "Crops",
    "Culinary Arts",
    "Dreamers",
    "Elemental Forces",
    "Entertainment",
    "Fables",
    "Farming",
    "Folk Tales",
    "Fortunes",
    "Gateways",
    "Gleaming Structures",
    "Hidden Passageways",
    "Illusions",
    "Lighthouses",
    "Lore Keepers",
    "Merchant Halls",
    "Monopolies",
    "Mysticism",
    "Night Markets",
    "Oracles",
    "Overcrowding",
    "Pilgrimages",
    "Prophecies",
    "Public Works",
    "Quests",
    "Rituals",
    "Rumors",
    "Ruins",
    "Sanctuaries",
    "Secret Societies",
    "Street Performers",
    "Subcultures",
    "Surveillance",
    "Taverns",
    "Wharfs",
]
list_cityEvents = [
    # Random Activity
    "ACTIVITIES",
    # Random Delusion
    "DELUSIONS",
    # Random Disaster
    "DISASTERS",
    # Random Faction
    "FACTIONS war",
    # Random Mutation
    "MUTATIONS",
    # Random TravelShift
    "TRAVEL-SHIFTS",
    "Abduction",
    "ANIMALS migration",
    "Annexation",
    "Arson",
    "Art exhibition",
    "Awakening of an ancient power",
    "Banishment",
    "Black market expansion",
    "Blood moon festival",
    "Bounty announcement",
    "Charity drive",
    "Civil unrest",
    "Coin shortage",
    "Colony establishment",
    "Cultural exchange",
    "Curse lifting",
    "Diplomatic visit",
    "Disaster relief",
    "Drug bust",
    "Economic boom",
    "Elopement",
    "Enlightenment festival",
    "Exploration expedition",
    "Festival of lights",
    "Fireworks display",
    "Fortune-telling fair",
    "Gambling competition",
    "Ghost sightings",
    "Harvest celebration",
    "Heist",
    "Honorary day",
    "Independence day",
    "Insurrection",
    "Karaoke night",
    "Labor strike",
    "Market expansion",
    "Mysterious disappearance",
    "New market opening",
    "Outbreak of disease",
    "Public hanging",
    "Rally for justice",
    "Religious pilgrimage",
    "Renaissance fair",
    "Riot control",
    "Ritual sacrifice",
    "Scavenger hunt",
    "Sponsorship of public works",
    "Theft",
    "Trade negotiations",
    "Trial by combat",
]
list_streetDetails = [
    # Random Activity
    "ACTIVITIES",
    # Random Animals
    "ANIMALS",
    # Random Building
    "BUILDINGS",
    # Random Hazard
    "HHAZARDS",
    # Random MiscItems
    "MISC-ITEMS",
    # Random PlaceTrait
    "PLACE-TRAITS",
    # Random Profession
    "PROFESSIONS",
    # Random RoomDetail
    "ROOM-DETAILS",
    "Abandoned buildings",
    "Alleyways",
    "Animal tracks",
    "Art installations",
    "Barrels",
    "Banners",
    "Bicycle racks",
    "Billboards",
    "Birdcages",
    "Bubbling springs",
    "Chalk drawings",
    "Chests",
    "Cobbled paths",
    "Courtyards",
    "Cracked pavement",
    "Decorative tiles",
    "Doorways",
    "Drainage grates",
    "Electrical wires",
    "Embers",
    "Faded signs",
    "Fences",
    "Flower pots",
    "Foliage",
    "Footprints",
    "Graffiti murals",
    "Hanging plants",
    "Hidden doorways",
    "Horseshoes",
    "Huddled groups",
    "Ice vendor carts",
    "Ice sculptures",
    "Kiosks",
    "Knotted ropes",
    "Laneways",
    "Leaf piles",
    "Marble statues",
    "Nooks and crannies",
    "Old coins",
    "Ornate gates",
    "Outdoor markets",
    "Overhanging signs",
    "Pavement cracks",
    "Pet bowls",
    "Public notice boards",
    "Rusty chains",
    "Sidewalk cafés",
    "Silhouettes",
    "Tattered flags",
    "Water troughs",
]
list_buildings = [
    # Random Dungeon
    "DUNGEONS",
    # Random Inn
    "INN-NAMEOneINN-NAMETwo",
    # Random Room
    "ROOMS",
    # Random Structure
    "STRUCTURES",
    "Amphitheater",
    "Armory",
    "Artisan workshop",
    "Bakery",
    "Barracks",
    "Bathhouse",
    "Blacksmith forge",
    "Brickyard",
    "Cafeteria",
    "Candle shop",
    "Carriage house",
    "Castle",
    "Chapel",
    "Chariot factory",
    "Circus",
    "Cloister",
    "Coliseum",
    "Confectionery",
    "Consulate",
    "Courthouse",
    "Dairy",
    "Dockyard",
    "Fabrics factory",
    "Fire station",
    "Foundry",
    "Granary",
    "Greenhouse",
    "Haven",
    "Inn",
    "Observatory",
    "Oratory",
    "Parliament",
    "Pavilion",
    "Pilgrims' lodge",
    "Plaza",
    "Power plant",
    "Prison",
    "Quarry",
    "Ranch",
    "Retreat",
    "Sanctuary",
    "Scribe’s workshop",
    "Shipwright's shop",
    "Smuggler's hideout",
    "Stadium",
    "Tower",
    "Trophy room",
    "University",
    "Watchtower",
    "Wishing well",
]

list_innNameOne = [
    "ACTIVITIES",
    "COLORS",
    "PLACE-TRAITS",
    "TRAITS-FOOD",
    "ITEM-TRAITS",
    "MONSTER-TRAITS",
    "QUALITIES",
    "FABRICS",
    "SOUNDS",
]
list_innNameTwo = [
    "ANIMALS",
    "MONSTERS",
    "CLOTHING",
    "FOODS",
    "MISC-ITEMS",
    "MONSTERS",
    "PROFESSIONS",
    "WEAPONS",
]
list_factions = [
    "CAREERS guild",
    "Animal whisperers",
    "Arcane order",
    "Archers' league",
    "Assassin's brotherhood",
    "Astronomers’ society",
    "Baronial council",
    "Beast tamers",
    "Black market traders",
    "Blood cult",
    "Bounty hunters",
    "Cavalry unit",
    "Charitable foundation",
    "Cloistered monks",
    "Conspiracy of mages",
    "Craftsmen's union",
    "Crusader knights",
    "Demon slayers",
    "Dragon riders",
    "Dream weavers",
    "Elementalists’ council",
    "Ethereal beings",
    "Fey court",
    "Fishermen's alliance",
    "Flamekeepers",
    "Fortune seekers",
    "Freemasons",
    "Golem crafters",
    "Harpers’ league",
    "Infiltrators’ network",
    "Knights of valor",
    "Loyalists",
    "Mystic order",
    "Nature's defenders",
    "Nightwatch",
    "Oracle’s cabal",
    "Outcast society",
    "Puppet masters",
    "Rabble rousers",
    "Royal court",
    "Scribes' circle",
    "Shadow syndicate",
    "Spellbinders",
    "Trade federation",
    "Warrior clan",
    "Witch hunters",
]
list_factionTraits = [
    "ACTIVITIES",
    # Random Personality
    "PERSONALITIES",
    "Adept",
    "Ambitious",
    "Archaic",
    "Autocratic",
    "Benevolent",
    "Chaotic",
    "Compassionate",
    "Conflicted",
    "Conservative",
    "Devoted",
    "Disgraced",
    "Eccentric",
    "Fanatic",
    "Flamboyant",
    "Gritty",
    "Indifferent",
    "Insidious",
    "Intrepid",
    "Loyal",
    "Visionary",
]
list_missions = [
    # Random Goal
    "GOALS",
    "Ally with FACTIONS",
    "Annihilate cult",
    "Appraise artifact",
    "Assassinate target",
    "Bargain with FACTIONS",
    "Befriend creature",
    "Bolster defenses",
    "Brave the wilds",
    "Capture stronghold",
    "Collect bounty",
    "Convince villagers",
    "Create distraction",
    "Deliver message",
    "Disarm trap",
    "Discover secret",
    "Disrupt trade",
    "Eliminate threat",
    "Engage in tournament",
    "Escape ambush",
    "Escort caravan",
    "Examine ruins",
    "Expose traitor",
    "Fend off raiders",
    "Find hidden treasure",
    "Forge alliance",
    "Gather intelligence",
    "Gain audience",
    "Hunt mythical beast",
    "Investigate disturbances",
    "Join expedition",
    "Lead rebellion",
    "Learn forbidden lore",
    "Negotiate peace",
    "Obtain rare ingredient",
    "Offer protection",
    "Organize festival",
    "Participate in heist",
    "Negate curse",
    "Recover stolen item",
    "Recruit allies",
    "Rescue prisoner",
    "Sabotage rival",
    "Seal a pact",
    "Secure location",
    "Shut down operation",
    "Steal artifact",
    "Survey territory",
    "Uncover conspiracy",
    "Win a duel",
    "Wrest control",
]
list_rewards = [
    # Random Animal
    "ANIMALS",
    # Random Asset
    "ASSETS",
    # Random Building
    "BUILDINGS",
    # Random Dungeon
    "DUNGEONS",
    # Random Faction
    "FACTIONS ally",
    # Random Inn
    "INN-NAMEOneINN-NAMETwo",
    # Random Location
    "LOCATIONS",
    # Random Material
    "MATERIALS",
    # Random Monster
    "MONSTERS ally",
    # Random Potion
    "POTIONS",
    # Random Spell
    "CHAOS-SPELLS",
    # Random Structure
    "STRUCTURES",
    # Random Treasure
    "TREASURES",
    # Random Weakness
    "WEAKNESSES",
    # Random Weapon
    "WEAPONS"
    "Artifact",
    "Bounty reward",
    "Cursed item",
    "Faction membership",
    "Favors from allies",
    "Forged documents",
    "Gained reputation",
    "Gems",
    "Grimoire",
    "Hidden treasure",
    "Invaluable information",
    "Legendary weapon",
    "Map",
    "Magical boon",
    "Monetary compensation",
    "Mystical creature companion",
    "New abilities",
    "Official title",
    "Political influence",
    "Potion",
    "Rare materials",
    "Recipe",
    "Reputation boost",
    "Resources",
    "Royal decree",
    "Safe passage",
    "Secret knowledge",
    "Shield of protection",
    "Spells",
    "Steed",
    "Surveillance tools",
    "Temporary truce",
    "Trade routes",
    "Treasure map",
    "Unbreakable contract",
    "Vial of rare potion",
    "Weapon enhancements",
    "Wealthy patron",
    "Writ of passage",
    "Year of protection",
    "Acclaimed title",
    "Artifact restoration",
    "Bounty on rival",
    "Cultural artifact",
    "Diminishing curse",
    "Historical insights",
    "Influential ally",
    "Key to secrets",
    "Master craftsman services",
    "Vision of the future",

]

list_maleNames = [
    "Albin",
    "Aldric",
    "Alistair",
    "Ansel",
    "Archimedes",
    "Augustus",
    "Balthus",
    "Baron",
    "Blaise",
    "Cadmus",
    "Caius",
    "Cassian",
    "Corvin",
    "Cyrano",
    "Cyril",
    "Dorian",
    "Edmund",
    "Edrick",
    "Eldred",
    "Emory",
    "Gaius",
    "Gareth",
    "Gideon",
    "Hector",
    "Hugo",
    "Icarus",
    "Isidore",
    "Jareth",
    "Kendrick",
    "Lysander",
    "Magnus",
    "Malcolm",
    "Nicodemus",
    "Oberon",
    "Octavian",
    "Orlando",
    "Pax",
    "Roderick",
    "Ronan",
    "Sampson",
    "Sirius",
    "Titus",
    "Tobias",
    "Ulric",
    "Victor",
    "Viggo",
    "Wilfred",
    "Xerxes",
    "Yannick",
    "Zephyr",
]
list_femaleNames = [
    "Adeline",
    "Althea",
    "Aveline",
    "Beatrice",
    "Belinda",
    "Blythe",
    "Briony",
    "Calista",
    "Celestine",
    "Clara",
    "Clementine",
    "Dahlia",
    "Delphine",
    "Desdemona",
    "Diana",
    "Elara",
    "Elysia",
    "Emmeline",
    "Felicity",
    "Fiora",
    "Flora",
    "Genevieve",
    "Gwendolyn",
    "Hester",
    "Isadora",
    "Juniper",
    "Lysandra",
    "Mabel",
    "Marcella",
    "Mirabel",
    "Nerine",
    "Octavia",
    "Ophelia",
    "Penelope",
    "Philippa",
    "Rhiannon",
    "Rowena",
    "Seraphina",
    "Sophronia",
    "Tatiana",
    "Theodora",
    "Thessaly",
    "Valentina",
    "Verity",
    "Vespera",
    "Yseult",
    "Zelda",
    "Zinnia",
    "Zosia",
    "Zuleika",
]
list_wizardNames = [
    # Random Surname
    "pSURNAME",
    "Althirian",
    "Astrogath",
    "Baltharion",
    "Belmistris",
    "Brimloth",
    "Cadruvian",
    "Calsorak",
    "Celanthar",
    "Drakthul",
    "Draxion",
    "Elarindor",
    "Eldrinox",
    "Falrathen",
    "Fenstrel",
    "Galashtor",
    "Glinthar",
    "Gorathor",
    "Haldorak",
    "Ithralis",
    "Jandaric",
    "Kaldorath",
    "Kalmarin",
    "Kynthas",
    "Malistran",
    "Meridon",
    "Morndrax",
    "Nimralis",
    "Orthanis",
    "Phaedral",
    "Quinthar",
    "Reymlor",
    "Rivenmar",
    "Ryndarion",
    "Salarin",
    "Saranthas",
    "Sorinthal",
    "Taldorak",
    "Talgrim",
    "Thalorian",
    "Thyndral",
    "Ulmorak",
    "Velkithar",
    "Vexithor",
    "Wyltharion",
    "Xarveth",
    "Xelthorian",
    "Ygareth",
    "Zaltharion",
    "Zynaros",
    "Zyphorn",
]
list_surnameOne = [
    "Adder",
    "Apple",
    "Ash",
    "Bab",
    "Bag",
    "Bar",
    "Barrow",
    "Basker",
    "Beau",
    "Beetle",
    "Berry",
    "Bird",
    "Brandy",
    "Bright",
    "Brindle",
    "Bull",
    "Bux",
    "Caven",
    "Chelten",
    "Chester",
    "Chuff",
    "Chum",
    "Clod",
    "Cobble",
    "Cotten",
    "Cress",
    "Crom",
    "Cumber",
    "Dela",
    "Dig",
    "Draw",
    "Dreg",
    "Drol",
    "Dun",
    "Ever",
    "Fair",
    "Fallow",
    "Farthing",
    "Feather",
    "Ferns",
    "Fox",
    "Gird",
    "Grey",
    "Grim",
    "Grit",
    "Hart",
    "Haver",
    "Sedge",
    "Silver",
    "Tread",
]
list_surnameTwo = [
    "bald",
    "barrow",
    "batch",
    "beck",
    "blood",
    "bold",
    "bone",
    "bottle",
    "bottom",
    "bridge",
    "buck",
    "burn",
    "bury",
    "by",
    "caster",
    "castle",
    "chester",
    "child",
    "church",
    "cliff",
    "cloth",
    "coat",
    "combe",
    "cott",
    "dale",
    "dish",
    "ditch",
    "down",
    "fax",
    "feld",
    "fent",
    "fer",
    "field",
    "foot",
    "force",
    "fort",
    "fry",
    "gale",
    "grave",
    "green",
    "grove",
    "ham",
    "hill",
    "hope",
    "land",
    "less",
    "ling",
    "lock",
    "wood",
    "worth",
]
list_professions = [
    # Random Archetype
    "ARCHETYPES",
    "Abbot",
    "Blacksmith",
    "Cartographer",
    "Dancer",
    "Engineer",
    "Falconer",
    "Gardener",
    "Herbalist",
    "Innkeeper",
    "Jester",
    "Knight",
    "Locksmith",
    "Merchant",
    "Navigator",
    "Outlaw",
    "Poet",
    "Quarrier",
    "Ratcatcher",
    "Scribe",
    "Tailor",
    "Undertaker",
    "Vintner",
    "Witch",
    "Yeoman",
    "Zookeeper",
    "Acrobat",
    "Bard",
    "Cook",
    "Diplomat",
    "Fisherman",
    "Gambler",
    "Historian",
    "Investigator",
    "Jewelers",
    "Minstrel",
    "Notary",
    "Oracle",
    "Plumber",
    "Quester",
    "Ranger",
    "Sage",
    "Tinker",
    "Usher",
    "Vicar",
    "Whaler",
    "Xylophonist",
    "Yachtsman",
    "Zitherist",
    "Poetess",
    "Wizard",
]
list_npcDetails = [
    "Aged hands",
    "Angular jaw",
    "Ashen complexion",
    "Athletic build",
    "Bandaged hand",
    "Beady eyes",
    "Bristly beard",
    "Calloused palms",
    "Charcoal smudge",
    "Chubby cheeks",
    "Curvaceous figure",
    "Deep-set eyes",
    "Dimpled chin",
    "Distinctive birthmark",
    "Distorted features",
    "Eccentric clothing",
    "Elongated limbs",
    "Eruptive skin condition",
    "Faded tattoos",
    "Freckled nose",
    "Gaudy jewelry",
    "Grizzled hair",
    "Hunched shoulders",
    "Ink-stained fingers",
    "Jagged scar",
    "Jowly face",
    "Lopsided smile",
    "Messy bun",
    "Mismatched eyes",
    "Mottled skin",
    "Mulleted hair",
    "Pockmarked face",
    "Pouty lips",
    "Ragged clothing",
    "Reddish tint",
    "Ripped muscles",
    "Scarred arms",
    "Sallow complexion",
    "Scarred back",
    "Scuffed boots",
    "Shimmering eyes",
    "Smudged makeup",
    "Spiky hair",
    "Stooped posture",
    "Sunken cheeks",
    "Tanned skin",
    "Thick neck",
    "Tightly curled hair",
    "Twisted features",
    "Weather-beaten skin",
]
list_personalities = [
    # Random Archetype
    "ARCHETYPES",
    "Absent-minded",
    "Adventurous",
    "Affectionate",
    "Altruistic",
    "Ambitious",
    "Argumentative",
    "Articulate",
    "Benevolent",
    "Bold",
    "Carefree",
    "Cautious",
    "Charismatic",
    "Charming",
    "Cheerful",
    "Conscientious",
    "Cynical",
    "Determined",
    "Detached",
    "Diligent",
    "Discreet",
    "Eccentric",
    "Empathetic",
    "Enthusiastic",
    "Fearless",
    "Frugal",
    "Generous",
    "Grumpy",
    "Humble",
    "Idealistic",
    "Indecisive",
    "Innovative",
    "Introverted",
    "Irreverent",
    "Joyful",
    "Judgmental",
    "Kind-hearted",
    "Laid-back",
    "Melodramatic",
    "Mysterious",
    "Optimistic",
    "Outspoken",
    "Passionate",
    "Pessimistic",
    "Quirky",
    "Rational",
    "Rebellious",
    "Reserved",
    "Sensible",
    "Stubborn",
    "Tactful",
    "Xenophobic",
]

list_goals = [
    # Random Mission
    "MISSIONS",
    "Abolish tyranny",
    "Acquire knowledge",
    "Alleviate suffering",
    "Amass power",
    "Amplify influence",
    "Assassinate rival",
    "Atone for sins",
    "Balance nature",
    "Build community",
    "Build reputation",
    "Build sanctuary",
    "Champion justice",
    "Challenge authority",
    "Change society",
    "Chart uncharted lands",
    "Conserve resources",
    "Defend home",
    "Defend the innocent",
    "Defy expectations",
    "Develop technology",
    "Discover new realms",
    "Dismantle corruption",
    "Establish order",
    "Expand trade routes",
    "Experience adventure",
    "Expand territory",
    "Explore mysteries",
    "Fight for freedom",
    "Forge alliances",
    "Foster unity",
    "Gain enlightenment",
    "Guard secrets",
    "Inspire change",
    "Inspire loyalty",
    "Investigate mysteries",
    "Journey to enlightenment",
    "Learn lost arts",
    "Maintain peace",
    "Master diplomacy",
    "Nurture talent",
    "Overcome fear",
    "Promote harmony",
    "Pursue happiness",
    "Restore balance",
    "Restore lost glory",
    "Seek truth",
    "Shape destiny",
    "Stop injustice",
    "Uncover hidden knowledge",
    "Vanquish evil",
]
list_assets = [
    # Random Book
    "BOOKS expert",
    # Random Building
    "BUILDINGS",
    # Random Potion
    "POTIONS",
    "Potion stockpile",
    # Random Power
    "POWERS",
    # Random Profession
    "PROFESSIONS",
    # Random Spell
    "CHAOS-SPELLS",
    # Random Structure
    "STRUCTURES",
    "Abundant resources",
    "Ace pilot",
    "Alchemist workshop",
    "Ancient artifact",
    "Artifact collection",
    "Battle-hardened",
    "Benefactor",
    "Body double",
    "Bounty hunter",
    "Brilliant strategist",
    "Charismatic leader",
    "Connections in high places",
    "Court magician",
    "Cryptographer",
    "Dedicated followers",
    "Enchanted items",
    "Elite guard",
    "Exceptional negotiator",
    "Expert forger",
    "Fearless reputation",
    "Fleet of ships",
    "Forbidden knowledge",
    "Fortune teller",
    "Gifted musician",
    "Healing potions",
    "Historical records",
    "Illuminated manuscript",
    "Inventor",
    "Knowledgeable historian",
    "Master craftsman",
    "Merchant network",
    "Military strategist",
    "Mystical powers",
    "Notorious reputation",
    "Old family secrets",
    "Political connections",
    "Powerful artifacts",
    "Prodigy",
    "Protective wards",
    "Resourceful sidekick",
    "Sacred texts",
    "Skilled negotiator",
    "Spells of protection",
    "Trusted advisor",
    "Unbreakable vow",
    "Unseen support network",
    "Unmatched skills",
    "Wealthy benefactor",
    "Whisper network",
    "Worldly connections",
]
list_liabilities = [
    # Random Delusion
    "DELUSIONS",
    # Random Food
    "FOODS Addict",
    # Random MonsterTrait
    "MONSTER-TRAITS",
    # Random Mutation
    "MUTATIONS",
    # Random Scent
    "SCENTS",
    # Random Sound
    "SOUNDS",
    # Random Weakness
    "WEAKNESSES",
    "Absent-minded",
    "Addictive personality",
    "Agoraphobic",
    "Antisocial",
    "Arrogant",
    "Backstabber",
    "Belligerent",
    "Broken promises",
    "Clingy",
    "Co-dependent",
    "Compulsive shopper",
    "Conflicted loyalties",
    "Conspiracy theorist",
    "Cowardly",
    "Criminal record",
    "Delusional",
    "Dependent",
    "Desperate",
    "Disfigured",
    "Distrustful",
    "Easily manipulated",
    "Emotional wreck",
    "Erratic behavior",
    "Fearful",
    "Feckless",
    "Flaky",
    "Frequenting bad company",
    "Glib",
    "Grumpy",
    "Harsh critic",
    "Hoarder",
    "Impulsive",
    "Incompetent",
    "Insecure",
    "Intolerant",
    "Irresponsible",
    "Jeopardizes safety",
    "Lacks self-control",
    "Lethargic",
    "Manipulative",
    "Mercurial",
    "Misunderstood",
    "Moody",
    "Overbearing",
    "Overindulgent",
    "Pessimistic",
    "Reckless spender",
    "Reluctant to change",
    "Untrustworthy",
    "Whiny",
]
list_relationships = [
    "Accomplice",
    "Admirer",
    "Advocate",
    "Ally",
    "Amigo",
    "Associate",
    "Benefactor",
    "Bestie",
    "Betrayer",
    "Biographer",
    "Blood relative",
    "Body double",
    "Caregiver",
    "Collaborator",
    "Companion",
    "Confidante",
    "Contractor",
    "Co-worker",
    "Disciple",
    "Elder",
    "Ex-lover",
    "Friend of a friend",
    "Ghostwriter",
    "Housemate",
    "In-law",
    "Interrogator",
    "Mentor",
    "Neighbor",
    "Opponent",
    "Overlord",
    "Parent figure",
    "Peer",
    "Protector",
    "Proxy",
    "Rival",
    "Secret admirer",
    "Sibling-in-law",
    "Spokesperson",
    "Sponsor",
    "Strategist",
    "Subject",
    "Supporter",
    "Sweetheart",
    "Teacher's pet",
    "Troublemaker",
    "Trusted ally",
    "Underling",
    "Ward",
    "Witness",
    "Young protégé",
]
list_mannerisms = [
    # Random Archetype
    "ARCHETYPES",
    # Random Sound
    "SOUNDS",
    "Affected laughter",
    "Aggressive posture",
    "Airy tone",
    "Awkward gestures",
    "Bashful smiles",
    "Breathless speech",
    "Casual shrug",
    "Cheerful nods",
    "Constant fidgeting",
    "Dramatic sighs",
    "Droll expression",
    "Earnest gaze",
    "Evasive glances",
    "Exaggerated movements",
    "Fidgeting with hands",
    "Frequent interruptions",
    "Gruff voice",
    "Haughty laugh",
    "Hushed whispers",
    "Incessant nodding",
    "Intense eye contact",
    "Jittery fingers",
    "Long pauses",
    "Monotonous delivery",
    "Nervous tics",
    "Overly animated",
    "Pensive looks",
    "Persuasive tone",
    "Rapid gestures",
    "Repetitive phrases",
    "Restless shifting",
    "Sardonic smile",
    "Sassy retorts",
    "Self-conscious laughter",
    "Sighing heavily",
    "Slouching posture",
    "Soft-spoken",
    "Sulking demeanor",
    "Supercilious sneer",
    "Surprised eyebrows",
    "Swaying while talking",
    "Terse responses",
    "Thoughtful pauses",
    "Timid voice",
    "Touchy-feely",
    "Tragic expressions",
    "Upbeat tempo",
    "Vague hand gestures",
    "Whiny tone",
    "Wistful gazes",
]
list_archetypes = [
    "Abrasive journalist",
    "Absent-minded professor",
    "Acclaimed bard",
    "Adored monarch",
    "Affable rogue",
    "Anxious scribe",
    "Ardent reformer",
    "Belligerent mercenary",
    "Benevolent king",
    "Blasé aristocrat",
    "Bold treasure hunter",
    "Bumbling detective",
    "Charming scoundrel",
    "Child prodigy",
    "Cloistered monk",
    "Colorful storyteller",
    "Comedic actor",
    "Cunning diplomat",
    "Curious wanderer",
    "Cynical historian",
    "Daring thief",
    "Defiant soldier",
    "Devious merchant",
    "Despondent artist",
    "Determined crusader",
    "Diligent apprentice",
    "Disheveled alchemist",
    "Distrustful guard",
    "Dreamy visionary",
    "Droll librarian",
    "Eccentric inventor",
    "Eerie fortune-teller",
    "Fickle politician",
    "Fiery blacksmith",
    "Frustrated poet",
    "Gracious hostess",
    "Grumpy recluse",
    "Heroic champion",
    "Haughty socialite",
    "Impulsive gambler",
    "Inquisitive detective",
    "Jaded journalist",
    "Kind-hearted healer",
    "Melodramatic diva",
    "Mischievous sprite",
    "Outspoken activist",
    "Perceptive spy",
    "Quirky artist",
    "Stoic bodyguard",
    "Tenacious survivor",
]
list_monsters = [
    "ELEMENTS elemental",
    # Random Animal
    "ANIMALS",
    # Random Animal
    "Giant ANIMALS",
    "Animated MISC-ITEMS",
    "Animated WEAPONS",
    "Abominable snowman",
    "Aeolian harpy",
    "Alchemical homunculus",
    "Angel of death",
    "Anansi (trickster spider)",
    "Arachne (spider woman)",
    "Basilisk",
    "Bunyip",
    "Cecaelia (octopus-human hybrid)",
    "Charybdis",
    "Cockatrice",
    "Cyclops",
    "Djinn (genie)",
    "Dryad",
    "Ettin",
    "Fenrir (wolf)",
    "Fire-breathing dragon",
    "Frost giant",
    "Golem",
    "Grendel",
    "Harpy",
    "Hippocampus (horse-fish hybrid)",
    "Jabberwocky",
    "Kraken",
    "La Llorona (weeping woman)",
    "Leviathan",
    "Manticore",
    "Medusa",
    "Minotaur",
    "Nemean lion",
    "Nymph",
    "Ogre",
    "Oni (Japanese demon)",
    "Phantom",
    "Pixie",
    "Rakshasa",
    "Salamander",
    "Selkie (seal shapeshifter)",
    "Siren",
    "Skinwalker",
    "Specter",
    "Tarrasque",
    "Wendigo",
    "Wight",
    "Will-o'-the-wisp",
    "Yeti",
    "Zombie",
    "Zora (water-dwelling humanoid)",
    "Thunderbird",
    "Wyvern",
]
list_animals = [
    "Albatross",
    "Ant",
    "Antelope",
    "Armadillo",
    "Axolotl",
    "Badger",
    "Barracuda",
    "Bat",
    "Bear",
    "Bearded dragon",
    "Beetle",
    "Beluga whale",
    "Bison",
    "Blue jay",
    "Bongo (antelope)",
    "Butterfly",
    "Capybara",
    "Cassowary",
    "Cat",
    "Caterpillar",
    "Chicken",
    "Chinchilla",
    "Chinchilla",
    "Clam",
    "Clam",
    "Cobra",
    "Condor",
    "Corgi",
    "Cow",
    "Crow",
    "Crow",
    "Deer",
    "Dingo",
    "Dog",
    "Donkey",
    "Dromedary camel",
    "Duck",
    "Eagle",
    "Emu",
    "Falcon",
    "Ferret",
    "Ferret",
    "Fish",
    "Flamingo",
    "Fox",
    "Gecko",
    "Gibbon",
    "Giraffe",
    "Goat",
    "Goldfish",
    "Goldfish",
    "Guinea pig",
    "Guinea pig",
    "Hamster",
    "Hawk",
    "Hedgehog",
    "Hippopotamus",
    "Horse",
    "Hummingbird",
    "Ibex",
    "Jackrabbit",
    "Kangaroo",
    "Kiwi",
    "Ladybug",
    "Lemur",
    "Lizard",
    "Manatee",
    "Mouse",
    "Narwhal",
    "Ocelot",
    "Ostrich",
    "Parrot",
    "Pig",
    "Pigeon",
    "Platypus",
    "Quokka",
    "Quoll",
    "Rabbit",
    "Raccoon",
    "Rat",
    "Rattlesnake",
    "Robin",
    "Rooster",
    "Salamander",
    "Seahorse",
    "Sheep",
    "Snail",
    "Snake",
    "Sparrow",
    "Spider",
    "Squirrel",
    "Tapir",
    "Tarantula",
    "Tarantula",
    "Tortoise",
    "Turtle",
    "Wolf",
    "Wombat",
    "Yak",
    "Zebra",
]
list_organs = [
    "Acidic spines",
    "Adhesive pads",
    "Antlers",
    "Arms",
    "Beak",
    "Beard",
    "Belly pouch",
    "Bladder",
    "Brachiopod shell",
    "Cervical vertebrae",
    "Cilia",
    "Claspers",
    "Cloaca",
    "Crown",
    "Curved claws",
    "Defensive spines",
    "Ear flaps",
    "Excretory pore",
    "Fangs",
    "Fertilization sac",
    "Foot",
    "Gastric mill",
    "Glands",
    "Jaw",
    "Kidneys",
    "Larynx",
    "Limbs",
    "Mandibles",
    "Nasal passages",
    "Nerve endings",
    "Olfactory bulbs",
    "Ovaries",
    "Paddle",
    "Palps",
    "Paws",
    "Pelvis",
    "Pericardium",
    "Ribs",
    "Rudimentary wings",
    "Salivary glands",
    "Siphon",
    "Skeletal structure",
    "Skull",
    "Soft tissues",
    "Spinal column",
    "Stomach",
    "Thorns",
    "Tissue flaps",
    "Vocal cords",
    "Whiskers",
]
list_monsterTraits = [
    # Random Animal
    "ANIMALS form",
    # Random Color
    "COLORS",
    # Random Delusion
    "DELUSIONS",
    # Random Element
    "ELEMENTS skin",
    # Random Mannerism
    "MANNERISMS",
    # Random Mutation
    "MUTATIONS",
    # Random Organ
    "ORGANS",
    # Random Personality
    "PERSONALITIES",
    # Random Potion
    "POTIONS",
    # Random Power
    "POWERS",
    # Random Scent
    "SCENTS",
    # Random Sound
    "SOUNDS",
    # Random Tactic
    "TACTICS",
    # Random Texture
    "TEXTURES",
    # Random Weakness
    "WEAKNESSES"
    "Armored",
    "Beady eyes",
    "Blistering",
    "Burnished",
    "Chilling",
    "Chitinous",
    "Cloaked",
    "Cloudy",
    "Creeping",
    "Crimson",
    "Cryptic",
    "Cumbersome",
    "Cursed",
    "Deformed",
    "Demonic",
    "Diminutive",
    "Dizzying",
    "Echoing",
    "Enigmatic",
    "Erupting",
    "Fanged",
    "Foul-smelling",
    "Ghostly",
    "Glowing",
    "Greasy",
    "Hissing",
    "Inverted",
    "Intangible",
    "Invisible",
    "Jagged",
    "Knotty",
    "Malicious",
    "Mirrored",
    "Misty",
    "Mysterious",
    "Noxious",
    "Obsidian",
    "Overgrown",
    "Perpetual motion",
    "Phantom-like",
    "Quivering",
    "Radiant",
    "Repugnant",
    "Scaly",
    "Seething",
    "Shimmering",
    "Sinewy",
    "Twisted",
    "Veined",
    "Warped",
]
list_powers = [
    # Random Effect
    "EFFECTS",
    # Random Effect
    "EFFECTS aura",
    # Random Effect
    "EFFECTS blast",
    # Random Effect
    "EFFECTS bolt",
    # Random Effect
    "EFFECTS ray",
    "Electric aura",
    # Random Element
    "ELEMENTS aura",
    # Random Element
    "ELEMENTS blast",
    # Random Element
    "ELEMENTS bolt",
    # Random Element
    "ELEMS. breath",
    # Random Element
    "ELEMS. control",
    # Random Element
    "ELEMENTS ray",
    # Random Element
    "ELEMENTS wall",
    # Random Potion
    "POTIONS",
    # Random Spell
    "CHAOS-SPELLS",
    # Random TravelShift
    "TRAVEL-SHIFTS",
    "Absorb energy",
    "Aether manipulation",
    "Air control",
    "Amphibious",
    "Animate objects",
    "Antimagic field",
    "Arcane shield",
    "Aura of fear",
    "Aura of hope",
    "Blast wave",
    "Blindness",
    "Body swap",
    "Charm",
    "Cloud walking",
    "Confusion",
    "Control flames",
    "Control time",
    "Cryokinesis",
    "Detect thoughts",
    "Dimensional door",
    "Divine shield",
    "Dream manipulation",
    "Earth manipulation",
    "Elemental transformation",
    "Energy blast",
    "Fearful gaze",
    "Flesh armor",
    "Force manipulation",
    "Gravity well",
    "Illusion creation",
    "Invisibility",
    "Light manipulation",
    "Memory erase",
    "Mind shield",
    "Necromancy",
    "Night vision",
    "Phasing",
    "Precognition",
    "Psychic scream",
    "Rejuvenation",
    "Shadow teleportation",
    "Sonic scream",
    "Soul drain",
    "Space distortion",
    "Summon familiars",
    "Telekinesis",
    "Telepathy",
    "Weather control",
    "Web creation",
    "Wound closure",
]
list_scents = [
    # Random Animal
    "ANIMALS",
    # Random Food
    "FOODS",
    # Random Taste
    "TASTES",
    "Acid",
    "Alcohol",
    "Almond",
    "Ammonia",
    "Baby powder",
    "Balsamic",
    "Barnyard",
    "Bitter",
    "Blood",
    "Burnt hair",
    "Burnt rubber",
    "Cedarwood",
    "Chlorine",
    "Cigarette ash",
    "Damp earth",
    "Dog fur",
    "Exhaust",
    "Fish",
    "Gasoline",
    "Gunpowder",
    "Hay",
    "Herbal",
    "Incense",
    "Leather",
    "Licorice",
    "Mold",
    "Musk",
    "Old books",
    "Ozone",
    "Paint",
    "Pine",
    "Popcorn",
    "Rain",
    "Resinous",
    "Rotting wood",
    "Sea breeze",
    "Sewage",
    "Skunk",
    "Sour milk",
    "Stagnant water",
    "Stale beer",
    "Sulfur",
    "Sweat",
    "Tea",
    "Turpentine",
    "Vanilla",
    "Violets",
    "Wet concrete",
    "Wood smoke",
    "Worn-out shoes",
]
list_sounds = [
    # Random Activity
    "ACTIVITIES",
    # Random Animal
    "ANIMALS",
    # Random Mannerism
    "MANNERISMS",
    "Barking",
    "Beeping",
    "Belching",
    "Blasting",
    "Blipping",
    "Booming",
    "Bubbling",
    "Burping",
    "Chiming",
    "Chirping",
    "Chopping",
    "Clapping",
    "Clattering",
    "Clicking",
    "Clomping",
    "Clunking",
    "Crashing",
    "Crinkling",
    "Croaking",
    "Crunching",
    "Drumming",
    "Fizzling",
    "Fluttering",
    "Glugging",
    "Grumbling",
    "Gurgling",
    "Hacking",
    "Hissing",
    "Honking",
    "Howling",
    "Jabbering",
    "Jingling",
    "Lapping",
    "Mewing",
    "Munching",
    "Murmuring",
    "Panting",
    "Peeping",
    "Pinging",
    "Plopping",
    "Quacking",
    "Rapping",
    "Rattling",
    "Ripping",
    "Squealing",
    "Squelching",
    "Stammering",
    "Throbbing",
    "Tinkling",
    "Warbling",
]
list_tactics = [
    # Random Effect
    "EFFECTS",
    # Random TrapEffect
    "TRAP-EFFECTS",
    "Ambush from above",
    "Anchor",
    "Anticipate attack",
    "Barricade",
    "Bait",
    "Bash",
    "Batter shield",
    "Block escape",
    "Blitz",
    "Bluff",
    "Bolster defense",
    "Brace for impact",
    "Break formation",
    "Break morale",
    "Brawl",
    "Charge through",
    "Clash weapons",
    "Collapse ground",
    "Corner foe",
    "Counterstrike",
    "Crush",
    "Dash past",
    "Deflect",
    "Deny access",
    "Destroy cover",
    "Distract with noise",
    "Drag down",
    "Drain energy",
    "Fake surrender",
    "Fend off",
    "Force into choke point",
    "Grapple",
    "Ground enemy",
    "Harass",
    "Harpoon",
    "Headbutt",
    "Hem in",
    "Intercept",
    "Intimidate",
    "Jab",
    "Knockdown",
    "Lasso",
    "Outflank",
    "Overwhelm",
    "Pin down",
    "Pulverize",
    "Retreat under cover",
    "Sap strength",
    "Snipe",
    "Wound and retreat",
]
list_weaknesses = [
    # Random Animal
    "ANIMALS",
    # Random Color
    "COLORS",
    # Random Domain
    "DOMAINS",
    # Random Element
    "ELEMENTS",
    # Random Food
    "FOODS",
    # Random Hazard
    "HHAZARDS",
    # Random Ingredient
    "INGREDIENTS",
    # Random Location
    "LOCATIONS",
    # Random MagicSchool
    "MAGIC-SCHOOLS",
    # Random Material
    "MATERIALS",
    # Random MiscItem
    "MISC-ITEMS",
    # Random Profession
    "PROFESSIONS",
    # Random Scent
    "SCENTS",
    # Random Sound
    "SOUNDS",
    # Random Spell
    "CHAOS-SPELLS",
    # Random Symbol
    "SYMBOLS",
    # Random Tactic
    "TACTICS",
    # Random Tool
    "TOOLS",
    # Random TravelShift
    "TRAVELS-SHIFTS",
    # Random Treasure
    "TREASURES",
    # Random Weapon
    "WEAPONS",
    "Aging",
    "Alcohol",
    "Allergies",
    "Anxiety",
    "Betrayal",
    "Blunt weapons",
    "Bright light",
    "Cold iron",
    "Compassion",
    "Cowardice",
    "Darkness",
    "Disloyalty",
    "Distrust",
    "Doubt",
    "Ego",
    "Electricity",
    "Emotional attachment",
    "Envy",
    "Exhaustion",
    "Fear of heights",
    "Fire",
    "Fragile bones",
    "Greed",
    "Holy relics",
    "Ice",
    "Impatience",
    "Indecision",
    "Inexperience",
    "Iron",
    "Jealousy",
    "Loud noises",
    "Magic",
    "Mental instability",
    "Mistrust",
    "Overconfidence",
    "Pain",
    "Paranoia",
    "Peer pressure",
    "Poison",
    "Pride",
    "Psychic attacks",
    "Regret",
    "Running water",
    "Salt",
    "Self-doubt",
    "Silver",
    "Sunlight",
    "Temptation",
    "Vulnerable heart",
    "Weak constitution",
]

TABLES = {
    "ACTIVITIES": list_activities,
    "ANIMALS": list_animals,
    "ARCHETYPES": list_archetypes,
    "ASSETS": list_assets,
    "BOOKS": list_books,
    "BUILDINGS": list_buildings,
    "CAREERS": list_careers,
    "CAROUSING": list_carousing,
    "CHAOS-SPELLS": list_chaosSpells,
    "CITY-EVENTS": list_cityEvents,
    "CITY-THEMES": list_cityThemes,
    "CLOTHING": list_clothing,
    "COLORS": list_colors,
    "DECORATIONS": list_decorations,
    "DELUSIONS": list_delusions,
    "DELVE-SHIFTS": list_delveShifts,
    "DISASTERS": list_disasters,
    "DOMAINS": list_domains,
    "DUNGEONS": list_dungeons,
    "DUNGEON-HAZARDS": list_dungeonHazards,
    "EFFECTS": list_effects,
    "ELEMENTS": list_elements,
    "FEMALE-NAMES": list_femaleNames,
    "FABRICS": list_fabrics,
    "FACTIONT-RAITS": list_factionTraits,
    "FACTIONS": list_factions,
    "FOODS": list_food,
    "TRAITS-FOOD": list_foodTraits,
    "FORMS": list_forms,
    "GOALS": list_goals,
    "HHAZARDS": list_hazards,
    "INGREDIENTS": list_ingredients,
    "INN-NAME-ONE": list_innNameOne,
    "INN-NAME-TWO": list_innNameTwo,
    "ITEM-TRAITS": list_itemTraits,
    "LIABILITIES": list_liabilities,
    "LOCATIONS": list_locations,
    "MALE-NAMES": list_maleNames,
    "MAGIC-SCHOOLS": list_magicSchools,
    "MANNERISMS": list_mannerisms,
    "MATERIALS": list_materials,
    "MECHANISMS": list_mechanisms,
    "MISC-ITEMS": list_miscItems,
    "MISSIONS": list_missions,
    "MONSTER-TRAITS": list_monsterTraits,
    "MONSTERS": list_monsters,
    "MUTATIONS": list_mutations,
    "NPC-DETAILS": list_npcDetails,
    "NPC-REACTIONS": list_npcReactions,
    "ORGANS": list_organs,
    "PERSONALITIES": list_personalities,
    "PLACE-TRAITS": list_placeTraits,
    "POTIONS": list_potions,
    "POWERS": list_powers,
    "PROFESSIONS": list_professions,
    "QUALITIES": list_qualities,
    "RELATIONSHIPS": list_relationships,
    "REWARDS": list_rewards,
    "ROOM-DETAILS": list_roomDetails,
    "ROOM-THEMES": list_roomThemes,
    "ROOMS": list_rooms,
    "SCENTS": list_scents,
    "SIGNS": list_signs,
    "SOUNDS": list_sounds,
    "STREET-DETAILS": list_streetDetails,
    "STRUCTURES": list_structures,
    "SURNAME-ONE": list_surnameOne,
    "SURNAME-TWO": list_surnameTwo,
    "SYMBOLS": list_symbols,
    "TACTICS": list_tactics,
    "TASTES": list_tastes,
    "TEXTURES": list_textures,
    "TOOLS": list_tools,
    "TRAP-EFFECTS": list_trapEffects,
    "TRAVEL-HAZARDS": list_travelHazards,
    "TRAVEL-SHIFTS": list_travelShifts,
    "TREASURES": list_treasures,
    "WEAKNESSES": list_weaknesses,
    "WEAPONS": list_weapons,
    "WEATHER": list_weather,
    "WIZARD-NAMES": list_wizardNames,
}

SECRETS = {
    "sROOM": secret_room,
    "sINGREDIENT": secret_ingredient,
}

preset_weather = [
        list_weather[dice_roll(6, 2)-2]
]


preset_reactions = [
        list_npcReactions[dice_roll(6, 2)-2]
]

preset_weather = [
        list_weather[dice_roll(6, 2)-2]
]


preset_reactions = [
        list_npcReactions[dice_roll(6, 2)-2]
]

PRESETS = {
    "pHEXCRAWL": preset_hexcrawl,
    "pSURNAME": preset_surname,
    "pINNNAME": preset_innName,
    "pFOOD": preset_food,
    "pCLOTHES": preset_clothes,
    "pDUNGEON": preset_dungeon,
    "pPOTION": preset_potion,
    "pCITY": preset_city,
    "pTRAP": preset_triplemechanismtrap,
    "pWEATHER": preset_weather,
    "pREACTIONS": preset_reactions,
}

masterTable: dict[str, list[Any]] = {}
masterTable.update(TABLES)
masterTable.update(SECRETS)
masterTable.update(PRESETS)
